project:
  type: website
  output-dir: docs
  resources:
    - images/

website:
  title: "Health Facility Data Portal"
  back-to-top-navigation: true
  favicon: images/hf_logo.png

  page-footer:
    left: "Copyright 2026, HF Portal"
    right: "Sponsored by ![](images/gates.png){height=26px style='margin-left:8px;'}"
    background: primary

  navbar:
    search: true
    logo: images/hf_logo.png
    logo-alt: "Structured HF data for malaria-endemic African countries"
    logo-href: /index.html
    pinned: true
    tools:
      - icon: github
        href: https://github.com/myalla-christina/hf-data-portal
        aria-label: GitHub
    right:
      - text: " "
        href: index.qmd
        icon: house-door-fill
      - text: About
        href: about.qmd
      - text: Countries
        menu:
          - text: "Tanzania"
            href: countries/tanzania.qmd
          - text: "Malawi"
            href: countries/Malawi.qmd
          - text: "Uganda"
            href: countries/uganda.qmd
          - text: "Zambia"
            href: countries/Zambia.qmd
          - text: "Benin"
            href: countries/Benin.qmd
          - text: "Botswana"
            href: countries/Botswana.qmd
          - text: "Nigeria"
            href: countries/Nigeria.qmd
      - text: Methods
        href: methodology.qmd
      - text: Roadmap
        href: roadmap.qmd
      - icon: globe
        href: https://map.ox.ac.uk
        aria-label: MAP Oxford

format:
  html:
    theme:
      light: [flatly, style-base.scss, style-light.scss]
      dark:  [darkly,  style-base.scss, style-dark.scss]
    toc: false
    link-external-icon: false
    link-external-newwindow: true

execute:
  freeze: auto
